# Generated by Django 4.2.6 on 2023-10-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='educator_feedback',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='resources',
        ),
        migrations.AddField(
            model_name='question',
            name='educator_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response_model',
            name='worksheet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.worksheet', verbose_name='Worksheet ID'),
        ),
    ]
