# Generated by Django 4.2.6 on 2023-10-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('standard', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('division', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('standard', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('premium_user', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1')])),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Email')),
                ('contact_no', models.CharField(blank=True, max_length=20, verbose_name='Contact No.')),
                ('guardian_name', models.CharField(blank=True, max_length=40, verbose_name="Parent's/Guardian's Name")),
                ('guardian_contact', models.CharField(blank=True, max_length=20, verbose_name="Parent's/Guardian's Contact No")),
                ('guardian_address', models.TextField(blank=True, max_length=150, verbose_name="Parent's/Guardian's Address")),
                ('school_name', models.TextField(blank=True, max_length=150, verbose_name='School Name')),
                ('forget_password_token', models.CharField(blank=True, max_length=4)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.classroom', verbose_name='Classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
